wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1657212926
    t:
      1:
      - 1
      - 5
      - 18
      - 41
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 18
      - 41
      - 53
      - 55
      - 71
      3:
      - 2
      - 13
      4: 3.9.12
      5: 0.12.20
      8:
      - 5
