wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1658424487
    t:
      1:
      - 1
      - 5
      - 18
      - 41
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 18
      - 41
      - 53
      - 55
      - 71
      3:
      - 13
      - 24
      4: 3.7.13
      5: 0.12.21
      8:
      - 6
